language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command for running testss
script:
  - pytest -vv --cov = post.py
#command for getting the test coverage
after_success:
  - coveralls